In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
df=pd.read_csv('train_logistic.csv')
is_male=pd.get_dummies(df['Sex'],drop_first=True)
df['is_male']=is_male
df["is_male"] = df["is_male"].astype(int)
df.drop(['Name','Sex'],axis=1,inplace=True)
x_train=df[["Pclass","Age","Siblings/Spouses Aboard","Parents/Children Aboard","Fare",'is_male']]
y_train=df["Survived"]
x_train=x_train.to_numpy()
y_train=y_train.to_numpy()
m,n=np.shape(x_train)
w=np.zeros((n,))
b=0
print(x_train)


[[ 3.     22.      1.      0.      7.25    1.    ]
 [ 1.     38.      1.      0.     71.2833  0.    ]
 [ 3.     26.      0.      0.      7.925   0.    ]
 ...
 [ 1.     39.      1.      0.     55.9     0.    ]
 [ 3.     18.      1.      0.     14.4583  0.    ]
 [ 3.     32.      0.      0.      7.925   1.    ]]


In [3]:
def z_score_normalise(x):
    mu=np.mean(x,axis=0)
    sigma=np.std(x,axis=0)
    x_norm=(x-mu)/sigma
    return x_norm,mu,sigma
x_train_norm,mu,sigma=z_score_normalise(x_train)


In [4]:
def sigmoid(x,w,b):
    m,n=np.shape(x)
    z=np.zeros((m,))
    for i in range(m):
        z[i]=np.dot(x[i],w)+b
    m=np.shape(z)[0]
    g_wb=np.ones((m,))
    g_wb*=(1/(1+np.exp(-z)))
    return g_wb

In [5]:
def compute_cost(x,y,w,b):
    '''m,n=np.shape(x)
    cost=0
    for i in range (m):
        cost=cost+ (np.dot(x[i],w)+b-y[i])**2
    cost/=(2*m)
    return cost'''

In [6]:
def compute_gradient_logistic(x,y,w,b):
    m,n=np.shape(x)
    g_wb=sigmoid(x,w,b)
    dj_dw=np.zeros((n,))
    dj_db=0
    err=g_wb-y
    dj_db=np.sum(err)
    for i in range(m):
        for j in range(n):
            dj_dw[j]+=err[i]*x[i,j]
    dj_dw/=m
    dj_db/=m
    print(dj_dw)
    print(dj_db)
    return dj_dw,dj_db

In [7]:
def gradient_descent(x,y,w,b,num_iters,alpha):
    j_history=[]
    for i in range(num_iters):
        dj_dw,dj_db=compute_gradient_logistic(x,y,w,b)
        w-=alpha*dj_dw
        b-=alpha*dj_db
        j_history.append(compute_gradient_logistic(x,y,w,b))
    return w,b,j_history   

In [8]:
iters=1000
alpha=0.1
w_fin,b_fin,j_hist=gradient_descent(x_train_norm,y_train,w,b,iters,alpha)


[ 0.13513782  0.0328393   0.02555627 -0.03981533 -0.09554636  0.27147432]
0.10311958405545928
[ 0.12984653  0.0329068   0.02627997 -0.0370243  -0.08995864  0.26368888]
0.10054176150300057
[ 0.12984653  0.0329068   0.02627997 -0.0370243  -0.08995864  0.26368888]
0.10054176150300057
[ 0.12479952  0.03294811  0.02692768 -0.03438533 -0.08465764  0.25616009]
0.09802940846382643
[ 0.12479952  0.03294811  0.02692768 -0.03438533 -0.08465764  0.25616009]
0.09802940846382643
[ 0.11999268  0.03296461  0.02750314 -0.0318938  -0.07964112  0.24888561]
0.09558195660043813
[ 0.11999268  0.03296461  0.02750314 -0.0318938  -0.07964112  0.24888561]
0.09558195660043813
[ 0.11542013  0.03295777  0.02801037 -0.02954438 -0.07490325  0.24186144]
0.09319886598721577
[ 0.11542013  0.03295777  0.02801037 -0.02954438 -0.07490325  0.24186144]
0.09319886598721577
[ 0.11107461  0.0329291   0.02845352 -0.0273312  -0.07043547  0.23508226]
0.09087958520536946
[ 0.11107461  0.0329291   0.02845352 -0.0273312  -0.07043547

In [9]:
df_test=pd.read_csv("test_logistic.csv")
is_male=pd.get_dummies(df_test['Sex'],drop_first=True)
df_test['is_male']=is_male
df["is_male"] = df["is_male"].astype(int)
df_test.drop(['Name','Sex'],axis=1,inplace=True)
x_test=df_test[["Pclass","Age","Siblings/Spouses Aboard","Parents/Children Aboard","Fare",'is_male']]
m,n=np.shape(x_test)
y_test=df_test[['Survived']]
x_test=x_test.to_numpy()
y_test=y_test.to_numpy().reshape((m,))
m,n=np.shape(x_test)
x_test_norm=(x_test-mu)/sigma
y_pred=np.zeros((m,))
g_wb=sigmoid(x_test_norm,w_fin,b_fin)
for i in range(m):
    if (g_wb[i]>=0.5):
        y_pred[i]=1
    else:
        y_pred[i]=0
y_pred=y_pred.astype(int)
print(y_test)
print(y_pred)
count=0
for i in range (m):
    if y_test[i]==y_pred[i]:
        count+=1
print(count)


[1 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 0
 0 1 0 0 1 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 1 1 1 0 1 0 1 0 1 0 1
 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 1
 1 1 0 0 0 0 1 0 0 1 1 0 0 0 0 1 1 1 1 1 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 0
 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 1 0 0 1 1 0 1
 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1
 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 1 0 0 1 1
 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 1 1 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 1 1 0
 0 0 1 1 0 0 0 0 0 0 1 0 1 0]
[1 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0
 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 1 0 1
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0
 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0
 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1

In [10]:
from sklearn import metrics 
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)) 


Accuracy: 0.8129032258064516
